name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Build the Docker image
      run: |
        docker build -t my-flask-app .

    - name: Run the Flask application
      run: |
        docker run -d -p 5000:5000 --name flaskapp my-flask-app

    - name: Run tests in the Docker container
      run: |
        docker run --rm my-flask-app python -m unittest discover

    - name: Cleanup
      if: always()
      run: docker rm -f flaskapp

  push_to_registry:

        needs: test
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        
        steps:
          - name: Check out the repo
            uses: actions/checkout@v4
          
          - name: Log in to Docker Hub
            uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
            with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
            with:
              images: gabriellft/laffitteassignment2
          
          - name: Build and push Docker image
            uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}

